sudo: required
services:
  - docker

before_install:
  - docker build -t dcgator8/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dcgator8/react-test npm test

after_success:
  - docker build -t dcgator8/todo-client ./client
  - docker build -t dcgator8/todo-server ./server
  - docker build -t dcgator8/todo-worker ./worker
  - docker build -t dcgator8/todo-nginx ./nginx
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push dcgator8/todo-client
  - docker push dcgator8/todo-server
  - docker push dcgator8/todo-worker
  - docker push dcgator8/todo-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-2-444083008588
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"