services:
  client:
    image: dcgator8/todo-client
    mem_limit: 128m
    hostname: client
  server:
    image: dcgator8/todo-server
    mem_limit: 128m
    hostname: server
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: dcgator8/todo-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  nginx:
    image: dcgator8/todo-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"